---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Prepare {{ beats__shippper }} config file
  template:
    src: "{{ beats__shippper }}-config.yml.j2"
    dest: /etc/{{ beats__shippper }}/{{ beats__shippper }}.yml
    backup: true
  notify:
    - restart beat

- name: Copy {{ beats__shippper }} modules
  template:
    src: "{{ beats__modules_sourcedir }}/{{ item }}"
    dest: /etc/{{ beats__shippper }}/modules.d/{{ item | basename | regex_replace('\.j2','') }}
    backup: true
  with_items:
    - "{{ beats__modules }}"
  when: beats__modules is defined
  notify:
    - restart beat

- name: Start and enable {{ beats__shippper }} service
  service:
    name: "{{ beats__package_map[ beats__shippper ] }}"
    enabled: yes
    state: started
  changed_when: False
